### ISSUE TITLE
Nuget Package Error on Xamarin Studio using a Mac

### ISSUE THREAD

**Issue by RickTheHat** [Bigsby/Xamarin.Forms.OAuth#4]
_Adding 'Xamarin.Forms.OAuth 1.0.2' to sociallogindemo.
Could not install package 'Xamarin.Forms.OAuth 1.0.2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._
- I did verify that it works using Visual Studio 2015 Community Edition

**Comment by Bigsby** [comment]
xamarinmac profile is not support. I'll try and make it supported onde I test this in Xamarin Studio on a Mac.

Thanks for pointing this out.

**Comment by Bigsby** [comment]
Having a closer look at this, there is no Xamarin.Forms support for Xamarin.Mac. When there is, I'll add it to the package supported profiles. If I don't remember to do it, drop me a line.
