### ISSUE TITLE
Add custom provider without authentication URL

### ISSUE THREAD

**Issue by teland94** [Bigsby/Xamarin.Forms.OAuth#5]
It useful for Google Contacts API (for example), it's not support using profile and https://www.google.com/m8/feeds/ scopes both in authorizing process.

**Comment by Bigsby** [comment]
Up look into it tonight.

**Comment by Bigsby** [comment]
Hi, could you be a little more specific here?

I'm looking into the documentation and Google Contacts API uses the same OAuth 2.0 authentication as all the other Google APIs.

https://developers.google.com/google-apps/contacts/v3/#specifying_a_version

OAuth protocol "stats" in the authentication URL.

**Comment by teland94** [comment]
You could try scopes special for Google Contacts and you see that profile and https://www.google.com/m8/feeds/ scopes are invalid in authorizing process together. That's why authentication URL not using here, only scope for Google Contacts. I think you could realize a feature that can return only access token without profile information.

**Comment by Bigsby** [comment]
Oh...that's another thing. You are talking about application authentication whereas the purpose of this library is to let user authenticate. I'll consider implementing application only authentication for the providers that support it.

Thank you for the suggestion.

**Comment by teland94** [comment]
Ok, I'm adjusting the code of this library for own tasks without your enhancements. Sorry for troubling. There are some API's that not using authentication URL but requiring an Google Account... Ok, that's all.

**Comment by Bigsby** [comment]
It's no trouble at all. I'm, actually, amazed at the  traction this has had. To do what you are saying, I'll have to do something that I've been meaning to do that is to make a core library that is Xamarin agnostic. Do I can implement it for WPF and Mac OS too. Will do that, next.

**Comment by teland94** [comment]
But thank you for developing this library for Xamarin, you saved me a lot of time. But we can't understand each other. I'm sorry.
